[package]
name = "wg-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
ipnetwork = "0.18.0"
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
serde_ini = "0.2.0"
serde_with = "1.8.1"
tokio = { version = "1.5.0", features = ["io-util", "process", "fs"] }
